### ISSUE TITLE
Notus scanner depot manquant installation gvm 22 impossible de suivre linstallation grace a la documentation #bug  #urgent

### ISSUE THREAD

**Issue by backl1n** [greenbone/notus-scanner#465]
I try toi install but i stopped when i installation because i need directory archives but you have not directory archives in your repos in installation documentation you Say i need this

**Comment by backl1n** [comment]
@greenbonebot

**Comment by jjnicola** [comment]
Clossing the issue because it is not a bug, but an installation issue. If you have more question, please use the Greenbone Forum
